In [43]:
# Let's compute the V value for 3 states and 3 actions
# possible transition
import numpy as np
nan = np.nan
T = np.array([
    [[0.5,0.3,0.2],[0,0.9,0.1],[0,0,1]],
    [[0.1,0.7,0.2],[nan,nan,nan],[0.2,0,0.8]],
    [[1,0,0],[0.3,0.3,0.4],[nan,nan,nan]]
]
)

In [44]:
# possible reward
R = np.array([
    [[5,20,2],[0,15,1],[23,20,11]],
    [[13,9,1],[nan,nan,nan],[2,8,4]],
    [[1,0,0],[3,3,4],[nan,nan,nan]]
]
)

In [45]:
# possible actions
act = [[0,1,2],[0,2],[0,1]]

discount_fact = 0.6

In [56]:
# The value funcion
def value_function(discount_fact, T, R, act):
    V = np.zeros(3)
    for i in range(1000):
        V_pred = V.copy()
        for s in range(3):
            V[s]=np.max([np.sum([
                T[s,a,sprime]*(R[s,a,sprime]+discount_fact*V_pred[sprime]) for sprime in range(3)
            ]) for a in act[s]])
    return V

In [57]:
value_function(discount_fact, T, R, act)

array([25.00737947, 19.34650705, 16.00442768])

In [48]:
# Let's define the Q-value: Exploitation
def Q_function(discount_fact, T, R, act):
    Q = np.full((3,3), -np.inf)
    for i,j in enumerate(act):
        Q[i,j]=0
    for i in range(1000):
        Q_pred = Q.copy()
        for s in range(3):
            for a in act[s]:
                Q[s,a]=np.sum([T[s,a,sprime]*(R[s,a,sprime]+discount_fact*np.max(Q_pred[sprime])) for sprime in range(3)] )
                
    return Q

In [49]:
Q_function(discount_fact, T, R, act)

array([[21.80511643, 25.00737947, 20.60265661],
       [19.34650705,        -inf, 14.28301082],
       [16.00442768, 15.22476222,        -inf]])

In [50]:
# To find the policy

arg = Q_function(discount_fact, T, R, act)
list_argmax = np.argmax(arg, axis=1)
list_argmax

array([1, 0, 0])

In [52]:
# To implement TD learning algo : Randomly select action (Exploration) and state
def TD_function(discount_fact, lr, T, R, act):
    s = 0
    V = np.full(3, -np.inf)
    for i,j in enumerate(act):
        V[i]=0
    for i in range(1000):
        V_pred = V.copy()
        rand_act = np.random.choice(act[s])
        sprime = np.random.choice(range(3), p=T[s,rand_act])
                
        V[s]=(1-lr)*V_pred[s] + discount_fact*(R[s,rand_act,sprime]+V_pred[sprime]) 
        s = sprime
    return V

In [53]:
lr=0.8 
TD_function(discount_fact, lr, T, R, act) 

array([21.46345659, 12.81888473, 18.90400027])